[[redirects]]
  from = "/about.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/contact.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/media.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301